//------------------------------------------------------------------------------
// <auto-generated>
//     Stabilized manual settings wrapper for WinForms designer.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyCuaHangMayTinh.Properties
{
    internal sealed class Settings
    {
        private static readonly Settings defaultInstance = new Settings();

        public static Settings Default
        {
            get { return defaultInstance; }
        }

        public string QuanLyCuaHangMayTinhConnectionString
        {
            get
            {
                string cs = null;
                try
                {
                    cs = global::System.Configuration.ConfigurationManager.ConnectionStrings["DefaultConnection"]?.ConnectionString;
                    if (string.IsNullOrWhiteSpace(cs))
                        cs = global::System.Configuration.ConfigurationManager.ConnectionStrings["QuanLyCuaHangMayTinhConnectionString"]?.ConnectionString;
                }
                catch
                {
                }
                return string.IsNullOrWhiteSpace(cs)
                    ? "Data Source=.;Initial Catalog=QuanLyCuaHangMayTinhDB;Integrated Security=True;Encrypt=True;TrustServerCertificate=True"
                    : cs;
            }
        }

        public string DefaultConnection
        {
            get { return QuanLyCuaHangMayTinhConnectionString; }
        }
    }
}
